## Tensorflow 2
So, I thought why not learn tensorflow 2. TF1.x was a disaster that made to switch to PyTorch. 

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.14.0'

## Creating Tensors with tf.constant

In [5]:
tf.constant("Hello World")

2023-09-30 11:14:36.714243: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1886] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2428 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1050 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1


<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [6]:
tf.constant(True)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [7]:
zero_dim = tf.constant(5)
print(zero_dim)

tf.Tensor(5, shape=(), dtype=int32)


In [8]:
one_dim = tf.constant([1,2,3])
print(one_dim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [9]:
# if use even a single float, the whole array will be converted to float
two_dim = tf.constant([[1.0,2,3],[4,5,6]])
print(two_dim)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [10]:
three_dim = tf.constant([
    [[1.0,2,3],[4,5,6]],
    [[1.0,2,3],[4,5,6]],
    [[1.0,2,3],[4,5,6]]
])
print(three_dim.shape)
print(three_dim.ndim)

(3, 2, 3)
3


## Type casting

In [11]:
two_dim = tf.constant([[1.0, 2.1, 3.4]], dtype=tf.float16)
two_dim_casted = tf.cast(tf.constant([[1.0, 2.1, 3.4]]), dtype=tf.int16)
two_dim_casted_bool = tf.cast(tf.constant([[1.0, 2.1, 3.4]]), dtype=tf.bool)
print(two_dim.dtype)
print(two_dim_casted.dtype)
print(two_dim_casted_bool.dtype)

<dtype: 'float16'>
<dtype: 'int16'>
<dtype: 'bool'>


## Numpy to Tensor

In [12]:
np_array = np.array([1,2,4])
converted_tensor = tf.convert_to_tensor(np_array)

### Identity matrix tensor

In [13]:
tf.eye(3), tf.eye(3,4)

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]], dtype=float32)>)

In [14]:
tf.eye(3, batch_shape=[2])

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]], dtype=float32)>

### Fill tensor with a scalar value

In [15]:
tf.fill([2,3], 5)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[5, 5, 5],
       [5, 5, 5]], dtype=int32)>

In [16]:
tf.fill([2,3,3], 9)

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]]], dtype=int32)>

### Ones and zeros tensor

In [17]:
tf.ones([2,3]), tf.zeros([2,3])

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>)

### ones_like and zeros_like

In [18]:
print(tf.ones_like(two_dim))
print(tf.zeros_like(two_dim))

tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float16)
tf.Tensor([[0. 0. 0.]], shape=(1, 3), dtype=float16)


### Rank of a tensor

In [19]:
print(tf.rank(three_dim))

tf.Tensor(3, shape=(), dtype=int32)


### tf.shape() vs tf.size()

In [20]:
print(tf.shape(three_dim)) # shape of the tensor
print(tf.size(three_dim)) # number of total elements1

tf.Tensor([3 2 3], shape=(3,), dtype=int32)
tf.Tensor(18, shape=(), dtype=int32)


### Random values from a normal distribution

In [21]:
random_1 = tf.random.normal((3,2), mean=0, stddev=1)
print(random_1)

tf.Tensor(
[[ 0.55793685  0.04166941]
 [-0.29815245  0.12399716]
 [ 2.0323808   1.0330017 ]], shape=(3, 2), dtype=float32)


### Random values from a uniform distribution

In [22]:
random_2 = tf.random.uniform((3,2), minval=0, maxval=1)
print(random_2)

tf.Tensor(
[[0.37969685 0.8005668 ]
 [0.80394423 0.22233272]
 [0.84230614 0.9243933 ]], shape=(3, 2), dtype=float32)


In [23]:
tf.random.set_seed(1.0) # seeds the global random number generator
random_2 = tf.random.uniform((3,2), minval=0, maxval=1, seed=1.0)

print(random_2)

tf.Tensor(
[[0.05554414 0.01869845]
 [0.07080972 0.27141213]
 [0.65317714 0.58058167]], shape=(3, 2), dtype=float32)


### Indexing

In [24]:
tensor_indexing = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [25]:
print(tensor_indexing[5:])
print(tensor_indexing[-1:])
print(tensor_indexing[:-1])
print(tensor_indexing[5:-1])

tf.Tensor([ 6  7  8  9 10], shape=(5,), dtype=int32)
tf.Tensor([10], shape=(1,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor([6 7 8 9], shape=(4,), dtype=int32)


### matrix multiplication

In [26]:
matrix = tf.fill([3,3],5)
print(matrix)

tf.Tensor(
[[5 5 5]
 [5 5 5]
 [5 5 5]], shape=(3, 3), dtype=int32)


In [27]:
tf.linalg.matmul(matrix, tf.transpose(matrix)) # A.A^T

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[75, 75, 75],
       [75, 75, 75],
       [75, 75, 75]], dtype=int32)>

In [28]:
matrix = tf.eye(3)
matrix = tf.cast(matrix, dtype=tf.float64)
tf.linalg.inv(matrix) # inverse of I is I

2023-09-30 11:14:38.222107: I tensorflow/core/util/cuda_solvers.cc:179] Creating GpuSolver handles for stream 0x1c145cf0


<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])>

### SVD

In [29]:
s,u, v =  tf.linalg.svd(matrix) # singular value decomposition
print(s)
print(u)
print(v)

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float64)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float64)


## tensor to numpy

In [30]:
print(s.numpy())
print(u.numpy())
print(v.numpy())

[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Einstein summation

In [31]:
matrix = tf.fill([3,3],5)
print(tf.linalg.matmul(matrix, tf.transpose(matrix))) # A.A^T
print(tf.einsum('ij,jk->ik', matrix, tf.transpose(matrix))) # A.A^T

tf.Tensor(
[[75 75 75]
 [75 75 75]
 [75 75 75]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[75 75 75]
 [75 75 75]
 [75 75 75]], shape=(3, 3), dtype=int32)


# Einstein summation in Attention mechanism
Attention = softmax(QK^T/sqrt(d_k))V

In [32]:
Q = np.random.randn(32, 64, 512) # bqm
K = np.random.randn(32, 128, 512) # bkm

In [33]:
np.einsum('bqm, bkm -> bqk', Q, K).shape # bqk

(32, 64, 128)

## Einstein summation in Reformer paper [2020]

In [34]:
A = np.random.randn(2, 4, 4, 2) # bcij
B = np.random.randn(2, 4, 4, 1) # bcik

In [35]:
np.einsum('bcik, bcij -> bckj', B, A).shape # bckj

(2, 4, 1, 2)

### expand_dims -> add extra dims to tensors 

In [36]:
A = tf.random.normal((2, 2))
print(A.shape)

(2, 2)


In [37]:
tf.expand_dims(A, axis=0).shape

TensorShape([1, 2, 2])

In [38]:
tf.expand_dims(A, axis=1).shape

TensorShape([2, 1, 2])

### tf.squeeze

In [39]:
A = tf.random.normal((2, 2))
print(A.shape)
print(tf.squeeze(A).shape) # no squeeze

(2, 2)
(2, 2)


In [40]:
A = tf.random.normal((2, 1))
print(A.shape)
print(tf.squeeze(A).shape) # squeezed

(2, 1)
(2,)


### tf.reshape

In [41]:
A = tf.random.normal((2, 1))
print(A.shape)
print(tf.reshape(A, shape=([2,])).shape) # reshaped
print(tf.reshape(A, shape=([2,1,1])).shape) # reshaped

(2, 1)
(2,)
(2, 1, 1)


In [42]:
A = tf.random.normal((2, 1))
print(A.shape)
print(tf.concat([A, A, A], axis=0).shape) # row-wise concat
print(tf.concat([A, A, A], axis=1).shape) # column-wise concat

(2, 1)
(6, 1)
(2, 3)


## Ragged Tensors (python list)

In [43]:
ragged_tensor = tf.ragged.constant([[1,2,3],
                                    [4,5],
                                    [6,7,8,9]])

print(ragged_tensor.shape)
print(ragged_tensor)

(3, None)
<tf.RaggedTensor [[1, 2, 3], [4, 5], [6, 7, 8, 9]]>


## Sparse tensors

In [44]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0,0],[1,1],[2,2]],values=[1,1,1], dense_shape=[3,3]) # sparse tensor : identity matrix
print(sparse_tensor) # sparse tensor

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 1]
 [2 2]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 1 1], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))


In [45]:
print(tf.sparse.to_dense(sparse_tensor)) # convert to dense tensor

tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


In [46]:
## Variable tensors

In [47]:
x = tf.Variable([1])
print(x)

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([1], dtype=int32)>


In [48]:
x.assign([2])

<tf.Variable 'UnreadVariable' shape=(1,) dtype=int32, numpy=array([2], dtype=int32)>

## CPU vs GPU assignment

In [49]:
x.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [50]:
tf. config. list_physical_devices() # list of physical devices: not able to use GPU

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [53]:
# Int32 isn't supported by GPU; WHY?
with tf.device('GPU:0'):
    x = tf.Variable([1])

print(x.dtype)
print(x.device)        

<dtype: 'int32'>
/job:localhost/replica:0/task:0/device:CPU:0


In [54]:
# float32 is supported by GPU
with tf.device('GPU:0'):
    y = tf.Variable([1.0])

print(y.dtype)
print(y.device)

<dtype: 'float32'>
/job:localhost/replica:0/task:0/device:GPU:0
